[all:vars]
ansible_user = root
# либо ansible_user = ubuntu и ansible_become = true

[vpn_servers]
baal.t7g.org  ansible_host=94.177.202.216

[monitoring_servers]
# пока пусто, но сюда можно добавить graphite, prometheus и т.д.

[vcgnat_servers]
vcgnat-host.ttelecom.ru  ansible_host=194.8.47.5

# Группа для всех серверов
[infra:children]
vpn_servers
monitoring_servers
vcgnat_servers

[ttk_servers:children]
vcgnat_servers
