---
- name: Ensure FQDN is set in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s+'
    line: "127.0.1.1 {{ fqdn | default(inventory_hostname) }} {{ (fqdn | default(inventory_hostname)).split('.')[0] }}"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart networking services  # опционально

- name: Установить имя хоста (hostname)
  ansible.builtin.hostname:
    name: "{{ (fqdn | default(inventory_hostname)).split('.')[0] }}"
  notify: restart networking services

- name: Установить часовой пояс
  ansible.builtin.timezone:
    name: "{{ timezone }}"
  notify: restart cron

- name: Установить пакеты для диагностики и безопасности
  ansible.builtin.apt:
    name:
      - htop
      - iotop
      - ufw
      - fail2ban
    state: present
    update_cache: true

- name: Включить UFW
  community.general.ufw:
    state: enabled
  when: ufw_enabled | default(true)

- name: allow 'sudo' group to have passwordless sudo
  copy: 
    dest: "/etc/sudoers.d/sudo-group-nopasswd"
    content: | 
      %sudo ALL=(ALL:ALL) NOPASSWD: ALL
