---
- name: Ensure FQDN is set in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s+'
    line: "127.0.1.1 {{ fqdn | default(inventory_hostname) }} {{ (fqdn | default(inventory_hostname)).split('.')[0] }}"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart networking services  # optional
  tags: [common, hostname]

- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ (fqdn | default(inventory_hostname)).split('.')[0] }}"
  notify: restart networking services
  tags: [common, hostname]

- name: Set timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"
  notify: restart cron
  tags: [common, timezone]

- name: Install diagnostic and security packages
  ansible.builtin.apt:
    name:
      - htop
      - iotop
      - ufw
      - fail2ban
    state: present
    update_cache: true
  tags: [common, packages]

- name: Enable UFW
  community.general.ufw:
    state: enabled
  when: ufw_enabled | default(true)
  tags: [common, ufw]

- name: Allow 'sudo' group to have passwordless sudo
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/sudo-group-nopasswd"
    content: |
      %sudo ALL=(ALL:ALL) NOPASSWD: ALL
  tags: [common, sudo]
